//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinorityDashboard.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class deskdata_trans
    {
        public int tran_id { get; set; }
        public Nullable<int> desk_id { get; set; }
        public Nullable<int> scheme_id { get; set; }
        public Nullable<int> des_id { get; set; }
        public Nullable<int> fin_y_id { get; set; }
        public Nullable<int> sub_id { get; set; }
        public Nullable<int> est_id { get; set; }
        public Nullable<decimal> budgetary_provision_amt { get; set; }
        public Nullable<decimal> actual_allocation_amt { get; set; }
        public Nullable<decimal> actual_expenditure_amt { get; set; }
        public Nullable<decimal> actual_remaining_amt { get; set; }
        public Nullable<int> desk_officer_id { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
    }
}
