//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinorityDashboard.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class deskdata_trans_bak
    {
        public int tran_bak_id { get; set; }
        public Nullable<int> tran_id { get; set; }
        public Nullable<int> desk_id { get; set; }
        public Nullable<int> scheme_id { get; set; }
        public Nullable<int> des_id { get; set; }
        public Nullable<int> fin_y_id { get; set; }
        public Nullable<int> sub_id { get; set; }
        public Nullable<int> est_id { get; set; }
        public Nullable<decimal> committee_amount { get; set; }
        public Nullable<decimal> scheme_amount { get; set; }
    }
}
