//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinorityDashboard.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class deskdocument
    {
        public int deskdoc_id { get; set; }
        public Nullable<int> desk_id { get; set; }
        public Nullable<int> scheme_id { get; set; }
        public Nullable<int> des_id { get; set; }
        public Nullable<int> fin_y_id { get; set; }
        public Nullable<int> sub_id { get; set; }
        public Nullable<int> est_id { get; set; }
        public string doc_title { get; set; }
        public string doc_filename { get; set; }
    }
}
