//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinorityDashboard.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class district_scheme_details
    {
        public int id { get; set; }
        public int fin_y_id { get; set; }
        public int parent_scheme_id { get; set; }
        public int scheme_id_child1 { get; set; }
        public int scheme_id_child2 { get; set; }
        public int scheme_id_child3 { get; set; }
        public int imp_agency_id { get; set; }
        public Nullable<decimal> budgetary_provision_amt { get; set; }
        public Nullable<decimal> actual_allocation_amt { get; set; }
        public Nullable<decimal> actual_expenditure_amt { get; set; }
        public Nullable<decimal> actual_remaining_amt { get; set; }
        public string work_progress_desc { get; set; }
        public string file_upload { get; set; }
        public string utilization_certificate { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<int> des_id { get; set; }
    }
}
