//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinorityDashboard.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class grdetail
    {
        public int gr_id { get; set; }
        public string keywords_e { get; set; }
        public string keywords_m { get; set; }
        public System.DateTime gr_date { get; set; }
        public string unique_code_e { get; set; }
        public string unique_code_m { get; set; }
        public bool isactive { get; set; }
        public string gr_file { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
