//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinorityDashboard.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_trail
    {
        public int logintrailid { get; set; }
        public string userid { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> logintime { get; set; }
        public string loginmode { get; set; }
        public string status { get; set; }
        public string ipaddress { get; set; }
        public string loginstatusreason { get; set; }
        public string logintimedisplay { get; set; }
        public Nullable<System.DateTime> logouttime { get; set; }
    }
}
