//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinorityDashboard.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_master
    {
        public int menu_id { get; set; }
        public string menu_name { get; set; }
        public string controller_name { get; set; }
        public Nullable<bool> isactive { get; set; }
    }
}
