//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinorityDashboard.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MinorityDasboard_DBEntities : DbContext
    {
        public MinorityDasboard_DBEntities()
            : base("name=MinorityDasboard_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<desk_master> desk_master { get; set; }
        public virtual DbSet<district_master> district_master { get; set; }
        public virtual DbSet<financialyear_master> financialyear_master { get; set; }
        public virtual DbSet<scheme_master> scheme_master { get; set; }
        public virtual DbSet<subject_master> subject_master { get; set; }
        public virtual DbSet<estimation_master> estimation_master { get; set; }
        public virtual DbSet<deskdocument> deskdocuments { get; set; }
        public virtual DbSet<menu_master> menu_master { get; set; }
        public virtual DbSet<role_master> role_master { get; set; }
        public virtual DbSet<deskdata_trans_bak> deskdata_trans_bak { get; set; }
        public virtual DbSet<trans_docfile> trans_docfile { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<deskdata_trans> deskdata_trans { get; set; }
        public virtual DbSet<main_menu_master> main_menu_master { get; set; }
        public virtual DbSet<sub_menu_master> sub_menu_master { get; set; }
        public virtual DbSet<menu_role_mapping> menu_role_mapping { get; set; }
        public virtual DbSet<gallery_master> gallery_master { get; set; }
        public virtual DbSet<org_structure> org_structure { get; set; }
        public virtual DbSet<parentscheme> parentschemes { get; set; }
        public virtual DbSet<scheme_child1> scheme_child1 { get; set; }
        public virtual DbSet<scheme_child2> scheme_child2 { get; set; }
        public virtual DbSet<scheme_desc_mapping> scheme_desc_mapping { get; set; }
        public virtual DbSet<scheme_child3> scheme_child3 { get; set; }
        public virtual DbSet<scheme_child1_amt> scheme_child1_amt { get; set; }
        public virtual DbSet<scheme_child2_amt> scheme_child2_amt { get; set; }
        public virtual DbSet<parent_scheme_amt> parent_scheme_amt { get; set; }
        public virtual DbSet<scheme_child3_amt> scheme_child3_amt { get; set; }
        public virtual DbSet<implementation_agency_master> implementation_agency_master { get; set; }
        public virtual DbSet<district_scheme_details> district_scheme_details { get; set; }
        public virtual DbSet<scheme_amount_allocation> scheme_amount_allocation { get; set; }
        public virtual DbSet<grdetail> grdetails { get; set; }
    
        public virtual ObjectResult<GetDeskTransactionData_Result> GetDeskTransactionData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDeskTransactionData_Result>("GetDeskTransactionData");
        }
    
        public virtual ObjectResult<GetSubjectData_Result> GetSubjectData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSubjectData_Result>("GetSubjectData");
        }
    
        public virtual ObjectResult<GetDeskDocuments_Result> GetDeskDocuments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDeskDocuments_Result>("GetDeskDocuments");
        }
    
        public virtual ObjectResult<LoginByUsernamePassword_Result> LoginByUsernamePassword(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoginByUsernamePassword_Result>("LoginByUsernamePassword", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<CheckAuthorizeMenu_Result> CheckAuthorizeMenu(string username, string pageurl)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var pageurlParameter = pageurl != null ?
                new ObjectParameter("pageurl", pageurl) :
                new ObjectParameter("pageurl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CheckAuthorizeMenu_Result>("CheckAuthorizeMenu", usernameParameter, pageurlParameter);
        }
    
        public virtual ObjectResult<GetSchemeData_Result> GetSchemeData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSchemeData_Result>("GetSchemeData");
        }
    
        public virtual ObjectResult<GetSchemeDesc_Result> GetSchemeDesc(Nullable<int> pSchemeID, Nullable<int> schemeChild1, Nullable<int> schemeChild2, Nullable<int> schemeChild3)
        {
            var pSchemeIDParameter = pSchemeID.HasValue ?
                new ObjectParameter("PSchemeID", pSchemeID) :
                new ObjectParameter("PSchemeID", typeof(int));
    
            var schemeChild1Parameter = schemeChild1.HasValue ?
                new ObjectParameter("SchemeChild1", schemeChild1) :
                new ObjectParameter("SchemeChild1", typeof(int));
    
            var schemeChild2Parameter = schemeChild2.HasValue ?
                new ObjectParameter("SchemeChild2", schemeChild2) :
                new ObjectParameter("SchemeChild2", typeof(int));
    
            var schemeChild3Parameter = schemeChild3.HasValue ?
                new ObjectParameter("SchemeChild3", schemeChild3) :
                new ObjectParameter("SchemeChild3", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSchemeDesc_Result>("GetSchemeDesc", pSchemeIDParameter, schemeChild1Parameter, schemeChild2Parameter, schemeChild3Parameter);
        }
    
        public virtual ObjectResult<gp_amount_districtname_Result> gp_amount_districtname()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gp_amount_districtname_Result>("gp_amount_districtname");
        }
    
        public virtual ObjectResult<gp_amount_schemename_Result> gp_amount_schemename()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gp_amount_schemename_Result>("gp_amount_schemename");
        }
    
        public virtual ObjectResult<gp_district_scheme_details_Result> gp_district_scheme_details(Nullable<int> des_id)
        {
            var des_idParameter = des_id.HasValue ?
                new ObjectParameter("des_id", des_id) :
                new ObjectParameter("des_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gp_district_scheme_details_Result>("gp_district_scheme_details", des_idParameter);
        }
    
        public virtual ObjectResult<gp_GetAmount_Scheme_Result> gp_GetAmount_Scheme(Nullable<int> parent_scheme_id, Nullable<int> scheme_id_child1, Nullable<int> scheme_id_child2, Nullable<int> scheme_id_child3, Nullable<int> des_id, Nullable<int> fin_y_id)
        {
            var parent_scheme_idParameter = parent_scheme_id.HasValue ?
                new ObjectParameter("parent_scheme_id", parent_scheme_id) :
                new ObjectParameter("parent_scheme_id", typeof(int));
    
            var scheme_id_child1Parameter = scheme_id_child1.HasValue ?
                new ObjectParameter("scheme_id_child1", scheme_id_child1) :
                new ObjectParameter("scheme_id_child1", typeof(int));
    
            var scheme_id_child2Parameter = scheme_id_child2.HasValue ?
                new ObjectParameter("scheme_id_child2", scheme_id_child2) :
                new ObjectParameter("scheme_id_child2", typeof(int));
    
            var scheme_id_child3Parameter = scheme_id_child3.HasValue ?
                new ObjectParameter("scheme_id_child3", scheme_id_child3) :
                new ObjectParameter("scheme_id_child3", typeof(int));
    
            var des_idParameter = des_id.HasValue ?
                new ObjectParameter("des_id", des_id) :
                new ObjectParameter("des_id", typeof(int));
    
            var fin_y_idParameter = fin_y_id.HasValue ?
                new ObjectParameter("fin_y_id", fin_y_id) :
                new ObjectParameter("fin_y_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gp_GetAmount_Scheme_Result>("gp_GetAmount_Scheme", parent_scheme_idParameter, scheme_id_child1Parameter, scheme_id_child2Parameter, scheme_id_child3Parameter, des_idParameter, fin_y_idParameter);
        }
    }
}
