//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinorityDashboard.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class scheme_child1_amt
    {
        public int allotment_amt_child1_id { get; set; }
        public int fin_y_id { get; set; }
        public int parent_scheme_id { get; set; }
        public int scheme_id_child1 { get; set; }
        public Nullable<decimal> alloted_amount { get; set; }
        public Nullable<bool> isactive { get; set; }
    }
}
