//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinorityDashboard.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class trans_docfile
    {
        public int doc_file_id { get; set; }
        public Nullable<int> deskdoc_id { get; set; }
        public string doc_title { get; set; }
        public string doc_filename { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
