//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeContent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanguageResources.HomeContent", typeof(HomeContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string lblAbout {
            get {
                return ResourceManager.GetString("lblAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizen Charter.
        /// </summary>
        public static string lblCitizenCharter {
            get {
                return ResourceManager.GetString("lblCitizenCharter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string lblContact {
            get {
                return ResourceManager.GetString("lblContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Info.
        /// </summary>
        public static string lblDepartmentInfo {
            get {
                return ResourceManager.GetString("lblDepartmentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string lblGallery {
            get {
                return ResourceManager.GetString("lblGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GR/Act.
        /// </summary>
        public static string lblGRAct {
            get {
                return ResourceManager.GetString("lblGRAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goverment of Maharashtra.
        /// </summary>
        public static string lblHeaderSubTitle {
            get {
                return ResourceManager.GetString("lblHeaderSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINORITY DEVELOPMENT DEPARTMENT.
        /// </summary>
        public static string lblHeaderTitle {
            get {
                return ResourceManager.GetString("lblHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string lblHome {
            get {
                return ResourceManager.GetString("lblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Structure.
        /// </summary>
        public static string lblOrganizationStructure {
            get {
                return ResourceManager.GetString("lblOrganizationStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schemes.
        /// </summary>
        public static string lblSchemes {
            get {
                return ResourceManager.GetString("lblSchemes", resourceCulture);
            }
        }
    }
}
